---
- name: Check if dotfiles repository already exists
  ansible.builtin.stat:
    path: "{{ system_effective_user_dir | default(ansible_facts.user_dir) }}/dotfiles/.git"
  register: dotfiles_repo
  become: true
  become_user: "{{ system_effective_user_id | default(ansible_facts.user_id) }}"

- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: https://github.com/wittyjudge/dotfiles.git
    dest: "{{ system_effective_user_dir | default(ansible_facts.user_dir) }}/dotfiles"
    version: main
  when: not dotfiles_repo.stat.exists
  become: true
  become_user: "{{ system_effective_user_id | default(ansible_facts.user_id) }}"
