---
- name: Configure /etc/pacman.conf
  ansible.builtin.lineinfile:
    path: /etc/pacman.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backrefs: "{{ item.backrefs }}"
    state: present
  loop:
    - line: Color
      regexp: "^#?Color$"
      backrefs: true
    - line: ILoveCandy
      regexp: "^#?ILoveCandy$"
      backrefs: true
    - line: "ParallelDownloads = 5"
      regexp: "#ParallelDownloads"
      backrefs: true
  become: true

- name: Enable multilib repository in /etc/pacman.conf
  ansible.builtin.replace:
    path: /etc/pacman.conf
    regexp: '^#\[multilib\]\n#Include = /etc/pacman\.d/mirrorlist$'
    replace: "[multilib]\nInclude = /etc/pacman.d/mirrorlist"
  become: true

- name: Disable beep sound
  become: true
  block:
    - name: Disable pcspkr and snd_pcsp kernel modules
      community.general.modprobe:
        name: "{{ item }}"
        state: absent
      loop:
        - pcspkr
        - snd_pcsp
      failed_when: false

    - name: Blacklist pcspkr and snd_pcsp modules
      ansible.builtin.copy:
        dest: /etc/modprobe.d/nobeep.conf
        content: |
          blacklist pcspkr
          blacklist snd_pcsp
        owner: root
        group: root
        mode: "0644"

- name: Disable beep sound - blacklist pcspkr and snd_pcsp modules
  ansible.builtin.copy:
    dest: /etc/modprobe.d/nobeep.conf
    content: |
      blacklist pcspkr
      blacklist snd_pcsp
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Install required packages
  ansible.builtin.package:
    name:
      - base-devel
      - git
    state: present

- name: Check if yay is installed
  ansible.builtin.command: which yay
  register: system_yay_check
  changed_when: false
  failed_when: false

- name: Build and install yay
  when: system_yay_check.rc != 0
  become: false
  block:
    - name: Create temporary yay directory
      ansible.builtin.tempfile:
        state: directory
        suffix: yay
      register: system_yay_tmp

    - name: Clone yay repository
      ansible.builtin.git: # noqa: latest[git]
        repo: https://aur.archlinux.org/yay.git
        dest: "{{ system_yay_tmp.path }}"

    - name: Building yay
      ansible.builtin.command:
        cmd: makepkg -si --noconfirm
        chdir: "{{ system_yay_tmp.path }}"
      changed_when: true

    - name: Remove temporary yay directory
      ansible.builtin.file:
        path: "{{ system_yay_tmp.path }}"
        state: absent
